In [3]:
import pandas as pd
df =pd.read_csv('nepal_rental_dataset.csv')
df

,listing_id,title,monthly_rent_npr,price_raw,land_area,area_sqft_approx,road_size,road_width_ft,location,ward,...,no_of_flats,built_year,listing_date,status,description,images,num_images,city,url,source
0,9541,House for rent,75000.0,"रु.\r\n 75,...",3.5 aana Land,1197.88,14 ft Road,14.0,"Samakhusi 26 Kathmandu Metropolis Kathmandu, B...",26.0,...,2.5,2072,2026-07-09,Active,Prime location. Posh area.,https://www.gharghaderi.com/images/7733316642....,5,kathmandu,https://www.gharghaderi.com/house/9541-House-f...,gharghaderi.com
1,9464,"House on rent: Civil Homes Phase VII, Nagarjun-6",50000.0,"रु.\r\n 50,...",3 aana Land,1026.75,10 ft Road,10.0,"Sitapaila 6 Kathmandu Metropolis Kathmandu, Ba...",6.0,...,2.0,2075,2026-06-17,Active,A well-maintained house on 2.5 anna land is av...,https://www.gharghaderi.com/images/1385017984....,8,kathmandu,https://www.gharghaderi.com/house/9464-House-o...,gharghaderi.com
2,9361,4 BHK Semi Furnished House for Rent at Bhaisepati,119999.0,"रु.\r\n 1,1...",4.5 aana Land,1540.12,12 ft Road,12.0,"Bhaisepati 18 Kathmandu Metropolis Kathmandu, ...",18.0,...,2.5,2070,2026-04-20,Active,4BHK Semi Furninsed house on rent at Bhaisepat...,https://www.gharghaderi.com/images/9689349655....,8,kathmandu,https://www.gharghaderi.com/house/9361-4-BHK-S...,gharghaderi.com
3,9087,House on Rent at Koteswor for Office or Restau...,250000.0,"रु.\r\n 2,5...",11.5 Aana Land,3935.88,26 ft Road,26.0,"Koteswor 32 Kathmandu Metropolis Kathmandu, Ba...",32.0,...,2.5,2065,2026-02-07,Active,NaN,https://www.gharghaderi.com/images/3526587041....,1,kathmandu,https://www.gharghaderi.com/house/9087-House-o...,gharghaderi.com
4,9034,Fully-Furnished House on rent at Budhanilkantha,120000.0,"रु.\r\n 1,2...",4 aana Land,1369.00,13 ft Road,13.0,"Budhanilkantha Kathmandu Metropolis Kathmandu,...",NaN,...,NaN,Select Year,2026-01-29,Active,Fully-Furnished House on rent at Budhanilkanth...,https://www.gharghaderi.com/images/87854775.jp...,13,kathmandu,https://www.gharghaderi.com/house/9034-Fully-F...,gharghaderi.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,7548,House on sale at hepali golfutar sold,40000000.0,"रु.\r\n 4,0...",4.5 aana Land,1540.12,16 ft Road,16.0,"Galfutar Budhanilkantha Kathmandu, Bagmati",NaN,...,2.5,2078,2025-05-05,sold,Code:FHS222H House on sale at hepali 4.5 aana ...,https://www.gharghaderi.com/images/7218821637....,14,pokhara,https://www.gharghaderi.com/house/7548-House-o...,gharghaderi.com
306,6344,Beautiful 6 aana House For Sale in Pokhara,49000000.0,"रु.\r\n 4,9...",6 aana Land,2053.50,16 ft Road,16.0,"Chorepatan 17 Pokhara Metropolis Kaski, Gandaki",17.0,...,2.5,2072,2025-04-06,Active,Beautiful House in Pokhara located at Chorepat...,https://www.gharghaderi.com/images/8778255415....,2,pokhara,https://www.gharghaderi.com/house/6344-Beautif...,gharghaderi.com
307,3372,"4.5 Storey House On Sale. Nepaltar, Kathmandu ...",38000000.0,"रु.\r\n 3,8...",4 anna Land,NaN,13 ft Road,13.0,"tarksewor 04 Kathmandu Metropolis Kathmandu, S...",4.0,...,4.5,2073,2025-04-06,Active,If you want a Pre built House with Easy rentab...,https://www.gharghaderi.com/images/464659711.j...,4,pokhara,https://www.gharghaderi.com/house/3372-4.5-Sto...,gharghaderi.com
308,3748,4.1.1 ana house near Krishna Mandir imadol. Of...,30000000.0,"रु.\r\n 3,0...",1300sft Land,NaN,Only 2 kitta from 30 ft road Road,30.0,"Near Krishna Mandir imadol Mahalaxmi Lalitpur,...",3.0,...,3.0,2076,2025-04-06,Active,Contact no - 9866202143 325cr house is in offe...,https://www.gharghaderi.com/images/3879680883.jpg,1,pokhara,https://www.gharghaderi.com/house/3748-4.1.1-a...,gharghaderi.com
309,3096,House on Sale at Goldhunga Kathmandu,19000000.0,"रु.\r\n 1,9...",3 anna Land,NaN,13 ft Road,13.0,"Goldunga 04 Tarkeshwor Kathmandu, Bagmati",4.0,...,2.5,2070,2026-08-12,Active,Click to watch house video: Description Beauti...,https://www.gharghaderi.com/images/4842080471....,6,pokhara,https://www.gharghaderi.com/house/3096-House-o...,gharghaderi.com

In [5]:
df = df[df["district"] == "Kathmandu"].copy()
print("After filtering to Kathmandu district:", df.shape)

After filtering to Kathmandu district: (158, 36)

In [7]:
df.columns

Index(['listing_id', 'title', 'monthly_rent_npr', 'price_raw', 'land_area',
       'area_sqft_approx', 'road_size', 'road_width_ft', 'location', 'ward',
       'municipality', 'district', 'province', 'agent_or_owner', 'phone',
       'email', 'property_type', 'house_type', 'direction', 'bedrooms',
       'bathrooms', 'living_rooms', 'kitchens', 'total_rooms', 'parking',
       'built_up_sqft', 'no_of_flats', 'built_year', 'listing_date', 'status',
       'description', 'images', 'num_images', 'city', 'url', 'source'],
      dtype='str')

In [9]:
drop_cols = [
    "phone", "email", "url", "images", "agent_or_owner",  # not predictive
    "num_images",           # rarely meaningful for rent prediction
    "listing_date", "status",  #  not property characteristics
    "price_raw", "land_area", "road_size",  #  already parsed into numeric cols
    "province",             
]

In [11]:
df = df.drop(columns=[c for c in drop_cols if c in df.columns])
print("After dropping noise columns:", df.shape)
print("\nRemaining columns:", list(df.columns))

After dropping noise columns: (158, 24)

Remaining columns: ['listing_id', 'title', 'monthly_rent_npr', 'area_sqft_approx', 'road_width_ft', 'location', 'ward', 'municipality', 'district', 'property_type', 'house_type', 'direction', 'bedrooms', 'bathrooms', 'living_rooms', 'kitchens', 'total_rooms', 'parking', 'built_up_sqft', 'no_of_flats', 'built_year', 'description', 'city', 'source']

In [13]:
# Drop rows with no rent value at all (can't use these for supervised learning)
df = df[df["monthly_rent_npr"].notna()].copy()

In [15]:
 # anything below this is almost certainly a parsing error
df = df[df["monthly_rent_npr"] >= 3000].copy()

In [24]:
print("CITY:")
print(df["city"].value_counts(dropna=False))

print("\nDISTRICT:")
print(df["district"].value_counts(dropna=False))

print("\nMUNICIPALITY:")
print(df["municipality"].value_counts(dropna=False).head(30))

CITY:
city
kathmandu    114
bhaktapur     33
pokhara        8
lalitpur       1
Name: count, dtype: int64

DISTRICT:
district
Kathmandu    156
Name: count, dtype: int64

MUNICIPALITY:
municipality
NaN                                               62
Kathmandu Metropolis                              39
Baluwatar Kathmandu Metropolis                     6
Baneshwor Kathmandu Metropolis                     5
Dhumbarahi Kathmandu Metropolis                    4
Lazimpath Kathmandu Metropolis                     4
Maharajgunj Kathmandu Metropolis                   3
Tokha Kathmandu Metropolis                         3
Budhanilkantha Kathmandu Metropolis                2
Maitinagar Kathmandu Metropolis                    1
Imadol Kathmandu Metropolis                        1
Kalanki Kathmandu Metropolis                       1
Sano bharyang Kathmandu Metropolis                 1
chappalkarkhana Kathmandu Metropolis               1
mid baneshwor Kathmandu Metropolis                 1
Budhanilkanth Kathmandu Metropolis                 1
Cozy home Kathmandu Metropolis                     1
Dhapasi Kathmandu Metropolis                       1
Golfutar Budhanilkantha Kathmandu Metropolis       1
bishalnagar Kathmandu Metropolis                   1
Tahachal Kathmandu Metropolis                      1
bane Kathmandu Metropolis                          1
sifal Kathmandu Metropolis                         1
Ratopul Kathmandu Metropolis                       1
Bansbari Kathmandu Metropolis                      1
Mhepi Kathmandu Metropolis                         1
Tahchal Kathmandu Metropolis                       1
Near Neel Saraswati mandir Lalitpur Metropolis     1
Sukedhara Kathmandu Metropolis                     1
Bhainsepati Kathmandu Lalitpur Metropolis          1
Name: count, dtype: int64

In [26]:
df[df["city"].str.lower().isin(["pokhara", "kaski"])][
    ["listing_id", "location", "municipality", "district", "city"]
]

,listing_id,location,municipality,district,city
21,8272,chappalkarkhana Kathmandu Metropolis Kathmandu...,chappalkarkhana Kathmandu Metropolis,Kathmandu,pokhara
51,6428,"Baneshwor Kathmandu Metropolis Kathmandu, Bagmati",Baneshwor Kathmandu Metropolis,Kathmandu,pokhara
54,6067,"sifal Kathmandu Metropolis Kathmandu, Bagmati",sifal Kathmandu Metropolis,Kathmandu,pokhara
64,5210,"bishalnagar 4 Kathmandu Metropolis Kathmandu, ...",Kathmandu Metropolis,Kathmandu,pokhara
75,3942,"Sitapaila Milan Tole 4 Nagarjun Kathmandu, Sta...",NaN,Kathmandu,pokhara
305,7548,"Galfutar Budhanilkantha Kathmandu, Bagmati",NaN,Kathmandu,pokhara
307,3372,"tarksewor 04 Kathmandu Metropolis Kathmandu, S...",Kathmandu Metropolis,Kathmandu,pokhara
309,3096,"Goldunga 04 Tarkeshwor Kathmandu, Bagmati",NaN,Kathmandu,pokhara

In [30]:
kathmandu_locations = (
    df["city"].str.strip().str.lower().eq("pokhara")
    & df["location"].str.contains(
        "kathmandu|kathmandu metropolis|budhanilkantha|tarkeshwor|nagarjun",
        case=False,
        na=False
    )
)

df.loc[kathmandu_locations, "city"] = "kathmandu"

In [38]:
valley_cities = ["kathmandu", "lalitpur", "bhaktapur"]

df_valley = df[
    df["city"]
    .str.strip()
    .str.lower()
    .isin(valley_cities)
].copy()

print("Original rows:", len(df))
print("Kathmandu Valley rows:", len(df_valley))
print("Removed rows:", len(df) - len(df_valley))

Original rows: 156
Kathmandu Valley rows: 156
Removed rows: 0

In [40]:
print(df["city"].value_counts())

city
kathmandu    122
bhaktapur     33
lalitpur       1
Name: count, dtype: int64

In [42]:
# Check city vs district
pd.crosstab(
    df["city"].str.strip().str.lower(),
    df["district"].str.strip().str.lower()
)

district   kathmandu
city
bhaktapur         33
kathmandu        122
lalitpur           1

In [48]:
df.to_csv("nepal_rental_kathmandu_dataset.csv", index=False, encoding="utf-8-sig")